### ISSUE TITLE
Landing page build automation and deployment

### ISSUE THREAD

**Issue by andaaron** [project-zot/site-zot#8]
Build automation to:
- Build the landing page
- Build the documentation
- Publish both build results to project-zot.github.io so they can be available at zotregistry.io

**Comment by chofnar** [comment]
The two PRs below will build and push their resulting files to the project-zot.github,io repo, on the main branch.

Before merging and using them, the following setup is needed:
 - Generate a new ssh key with an email attached (perhaps a service account would come in handy here?)
 - On the docs-zot and zot-site repos, create a new secret named SSH_DEPLOY_KEY and put the private key in
 - On the project-zot.github.io repo, set the Deploy Key to the public key
 - Set the proper targets and users in the workflows (currently with mine for demo purposes)

PR with the docs build and push workflow:
https://github.com/project-zot/docs-zot/pull/69
PR with the landing page build and push workflow:
https://github.com/raulkele/zot-site/pull/6

Resulting repo:
https://github.com/chofnar/project-zot.github.io
And the github page:
https://chofnar.github.io/project-zot.github.io/
Docs page:
https://chofnar.github.io/project-zot.github.io/docs

**Comment by andaaron** [comment]
The keys have been configured. The PRs have been merged.
